using System.ComponentModel.DataAnnotations;

namespace Mission06LajicPajam.Models;

public class Movie
{
    // Primary key generated by SQLite.
    public int MovieId { get; set; }

    // Genre/category text entered by the user.
    [Required]
    public string Category { get; set; } = string.Empty;

    // Movie title shown in the confirmation and stored in the DB.
    [Required]
    public string Title { get; set; } = string.Empty;

    // Year captured as text in Mission 06's original schema.
    [Required]
    public string Year { get; set; } = string.Empty;

    // Director name for the submitted movie.
    [Required]
    public string Director { get; set; } = string.Empty;

    // Restrict ratings to the allowed values from the assignment.
    [Required]
    [RegularExpression("^(G|PG|PG-13|R)$", ErrorMessage = "Rating must be G, PG, PG-13, or R.")]
    public string Rating { get; set; } = string.Empty;

    // Nullable because the form allows "not specified".
    public bool? Edited { get; set; }

    // Optional person the movie is lent to.
    public string? LentTo { get; set; }

    // Optional notes capped at 25 characters by validation.
    [StringLength(25)]
    public string? Notes { get; set; }
}
